"""Generate the Kandinsky-style launcher icon.

One shape list drives both the Android vector drawable and a PNG preview, so
the preview is exactly what ships. Run:
    python tools/gen_icon.py [preview.png]   (preview needs Pillow)
"""
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

BG = "#F1E7CF"
INK = "#1B1B1B"

# Shapes in the 108x108 adaptive-icon viewport; the launcher mask shows
# roughly the central 72x72, so the composition stays inside 20..88.
SHAPES = [
    ("line", (18, 72), (90, 38), INK, 1.4),
    ("line", (32, 20), (84, 90), INK, 0.8),
    ("line", (22, 52), (40, 88), INK, 0.6),
    ("halfdisc", (32, 76), 9, "#2A9D8F", INK, 1.0),
    ("checker", (63, 60), 4, 3, ["#1B1B1B", "#F1E7CF", "#D62828"]),
    ("poly", [(70, 74), (80, 71), (82, 80), (72, 83)], "#6A4C93", INK, 0.8),
    ("circle", (77, 31), 6.5, "#D62828", INK, 1.2),
    ("circle", (77, 31), 2.6, "#F2B705", None, 0),
    ("circle", (30, 33), 3.2, INK, None, 0),
    # The map pin: a yellow triangle under a ring of concentric circles.
    ("poly", [(39, 49), (61, 49), (50, 85)], "#F2B705", INK, 1.2),
    ("circle", (50, 41), 19, "#F4A261", None, 0),
    ("circle", (50, 41), 15, "#1D3F8F", INK, 1.6),
    ("circle", (50, 41), 10, "#D62828", None, 0),
    ("circle", (50, 41), 5.5, "#F2B705", None, 0),
    ("circle", (50, 41), 2.2, INK, None, 0),
]


# Pull the whole composition toward the centre so round masks don't clip it.
SCALE, CX, CY = 0.8, 54, 57


def tp(p):
    return (CX + (p[0] - CX) * SCALE + 54 - CX, CY + (p[1] - CY) * SCALE + 54 - CY)


def transformed(shapes):
    out = []
    for s in shapes:
        kind = s[0]
        if kind == "line":
            out.append((kind, tp(s[1]), tp(s[2]), s[3], s[4] * SCALE))
        elif kind in ("circle", "halfdisc"):
            out.append((kind, tp(s[1]), s[2] * SCALE, s[3], s[4], s[5] * SCALE))
        elif kind == "poly":
            out.append((kind, [tp(q) for q in s[1]], s[2], s[3], s[4] * SCALE))
        elif kind == "checker":
            out.append((kind, tp(s[1]), s[2] * SCALE, s[3], s[4]))
    return out


SHAPES = transformed(SHAPES)


def fmt(v):
    return ("%.2f" % v).rstrip("0").rstrip(".")


def circle_path(c, r):
    cx, cy = c
    return (f"M{fmt(cx - r)},{fmt(cy)}a{fmt(r)},{fmt(r)} 0,1 0,{fmt(2 * r)},0"
            f"a{fmt(r)},{fmt(r)} 0,1 0,{fmt(-2 * r)},0z")


def vector_paths():
    out = []

    def path(d, fill=None, stroke=None, sw=0):
        attrs = [f'android:pathData="{d}"']
        if fill:
            attrs.append(f'android:fillColor="{fill}"')
        if stroke and sw:
            attrs += [f'android:strokeColor="{stroke}"', f'android:strokeWidth="{fmt(sw)}"',
                      'android:strokeLineCap="round"', 'android:strokeLineJoin="round"']
        out.append("    <path\n        " + "\n        ".join(attrs) + " />")

    for s in SHAPES:
        kind = s[0]
        if kind == "line":
            _, a, b, color, w = s
            path(f"M{fmt(a[0])},{fmt(a[1])}L{fmt(b[0])},{fmt(b[1])}", stroke=color, sw=w)
        elif kind == "circle":
            _, c, r, fill, stroke, w = s
            path(circle_path(c, r), fill, stroke, w)
        elif kind == "poly":
            _, pts, fill, stroke, w = s
            d = "M" + "L".join(f"{fmt(x)},{fmt(y)}" for x, y in pts) + "z"
            path(d, fill, stroke, w)
        elif kind == "halfdisc":
            _, (cx, cy), r, fill, stroke, w = s
            path(f"M{fmt(cx - r)},{fmt(cy)}A{fmt(r)},{fmt(r)} 0,0 1,{fmt(cx + r)},{fmt(cy)}z", fill, stroke, w)
        elif kind == "checker":
            _, (x0, y0), cell, n, colors = s
            for i in range(n):
                for j in range(n):
                    color = colors[2] if (i, j) == (1, 1) else colors[(i + j) % 2]
                    x, y = x0 + i * cell, y0 + j * cell
                    path(f"M{fmt(x)},{fmt(y)}h{fmt(cell)}v{fmt(cell)}h{fmt(-cell)}z", color)
            path(f"M{fmt(x0)},{fmt(y0)}h{fmt(n * cell)}v{fmt(n * cell)}h{fmt(-n * cell)}z",
                 stroke=colors[0], sw=0.6)
    return out


def write_vector(name, paths):
    xml = ('<?xml version="1.0" encoding="utf-8"?>\n'
           "<!-- Generated by tools/gen_icon.py; edit the script, not this file. -->\n"
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
           '    android:width="108dp"\n    android:height="108dp"\n'
           '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
           + "\n".join(paths) + "\n</vector>\n")
    (RES / "drawable" / name).write_text(xml)


def pin_silhouette():
    tri = next(sh for sh in SHAPES if sh[0] == "poly" and len(sh[1]) == 3)
    head = next(sh for sh in SHAPES if sh[0] == "circle" and sh[3] == "#F4A261")
    small = SHAPES[6]
    d = "M" + "L".join(f"{fmt(x)},{fmt(y)}" for x, y in tri[1]) + "z"
    return d + circle_path(head[1], head[2]) + circle_path(small[1], small[2])


def monochrome_paths():
    # Themed (Material You) icons are single-colour: just the pin silhouette.
    return [
        '    <path\n        android:fillColor="#000000"\n'
        f'        android:pathData="{pin_silhouette()}" />',
    ]


def render_preview(path, size=432):
    from PIL import Image, ImageDraw

    ss = 4
    k = size * ss / 108
    img = Image.new("RGB", (size * ss, size * ss), BG)
    d = ImageDraw.Draw(img)

    def P(p):
        return (p[0] * k, p[1] * k)

    for s in SHAPES:
        kind = s[0]
        if kind == "line":
            _, a, b, color, w = s
            d.line([P(a), P(b)], fill=color, width=max(1, round(w * k)))
        elif kind == "circle":
            _, (cx, cy), r, fill, stroke, w = s
            box = [(cx - r) * k, (cy - r) * k, (cx + r) * k, (cy + r) * k]
            d.ellipse(box, fill=fill, outline=stroke if w else None, width=max(1, round(w * k)) if w else 0)
        elif kind == "poly":
            _, pts, fill, stroke, w = s
            d.polygon([P(p) for p in pts], fill=fill, outline=stroke, width=max(1, round(w * k)))
        elif kind == "halfdisc":
            _, (cx, cy), r, fill, stroke, w = s
            box = [(cx - r) * k, (cy - r) * k, (cx + r) * k, (cy + r) * k]
            d.pieslice(box, 180, 360, fill=fill, outline=stroke, width=max(1, round(w * k)))
        elif kind == "checker":
            _, (x0, y0), cell, n, colors = s
            for i in range(n):
                for j in range(n):
                    color = colors[2] if (i, j) == (1, 1) else colors[(i + j) % 2]
                    x, y = x0 + i * cell, y0 + j * cell
                    d.rectangle([x * k, y * k, (x + cell) * k, (y + cell) * k], fill=color)
            d.rectangle([x0 * k, y0 * k, (x0 + n * cell) * k, (y0 + n * cell) * k],
                        outline=colors[0], width=max(1, round(0.6 * k)))
    img = img.resize((size, size), Image.LANCZOS)

    # Show it the way a launcher would: circle mask over the central 72/108.
    mask = Image.new("L", (size, size), 0)
    m = size * 18 / 108
    ImageDraw.Draw(mask).ellipse([m, m, size - m, size - m], fill=255)
    masked = Image.new("RGB", (size, size), "white")
    masked.paste(img, mask=mask)
    sheet = Image.new("RGB", (size * 2 + 16, size), "white")
    sheet.paste(img, (0, 0))
    sheet.paste(masked, (size + 16, 0))
    sheet.save(path)


if __name__ == "__main__":
    write_vector("ic_launcher_foreground.xml", vector_paths())
    write_vector("ic_launcher_monochrome.xml", monochrome_paths())
    if len(sys.argv) > 1:
        render_preview(sys.argv[1])
